### ISSUE TITLE
Dynamic Memory Management incurs error when running 4 instances on 2 * A100 GPUs

### ISSUE THREAD

**Issue by Ltryxcy** [ovg-project/kvcached#221]
When I launch four model instances—Qwen3-8B, Llama-3.1-8B, Llama-3.2-3B, and Qwen3-4B—on two A100 GPUs, the system raises a CUDA out-of-memory error and one instance face memory management error.
**The following commands are used to start these four servers:**
**Terminal 1:**
```
export CUDA_VISIBLE_DEVICES=0,1
export ENABLE_KVCACHED=true      
export KVCACHED_AUTOPATCH=1         
export VLLM_USE_V1=1           
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
vllm serve /mnt/Qwen3-8B --disable-log-requests --port 12346 --max_num_batched_tokens 4096 --tensor-parallel-size 2 --max-num-seqs 1024 --no-enable-prefix-caching --enforce-eager
```
**Terminal 2:**
```
export CUDA_VISIBLE_DEVICES=0,1
export ENABLE_KVCACHED=true     
export KVCACHED_AUTOPATCH=1          
export VLLM_USE_V1=1           
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
vllm serve /mnt/Meta-Llama-3.1-8B-Instruct --disable-log-requests --port 12347 --max_num_batched_tokens 4096 --tensor-parallel-size 2--max-num-seqs 256 --no-enable-prefix-caching --enforce-eager
```
**Terminal 3:**
```
export CUDA_VISIBLE_DEVICES=0
export ENABLE_KVCACHED=true
export KVCACHED_AUTOPATCH=1     
export VLLM_USE_V1=1       
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
vllm serve /mnt/Meta-Llama-3.2-3B --disable-log-requests --port 12348 --max_num_batched_tokens 4096 --tensor-parallel-size 1--max-num-seqs 256 --no-enable-prefix-caching --enforce-eager
```
**Terminal 4:**
```
export CUDA_VISIBLE_DEVICES=1
export ENABLE_KVCACHED=true 
export KVCACHED_AUTOPATCH=1          
export VLLM_USE_V1=1`            
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
vllm serve /mnt/Qwen3-4B --disable-log-requests --port 12349 --max_num_batched_tokens 4096 --tensor-parallel-size 1--max-num-seqs 256 --no-enable-prefix-caching --enforce-eager
```

**The following comands are used to start benchmarks:**
```
vllm bench serve --model /mnt/Qwen3-8B --dataset-name sharegpt --dataset-path /home/datasets/ShareGPT_V3_unfiltered_cleaned_split.json  --request-rate 12.48 --num-prompts 3744 --port 12346 --metric-percentiles "25,50,75,90,95,99" --seed 1620 --endpoint /v1/completions
vllm bench serve --model /mnt/Meta-Llama-3.1-8B-Instruct --dataset-name sharegpt --dataset-path /home/datasets/ShareGPT_V3_unfiltered_cleaned_split.json  --request-rate 6.24 --num-prompts 1872 --port 12347 --metric-percentiles "25,50,75,90,95,99" --seed 1620 --endpoint /v1/completions
vllm bench serve --model /mnt/llama-3.2-3B-Instruct --dataset-name sharegpt --dataset-path /home/datasets/ShareGPT_V3_unfiltered_cleaned_split.json  --request-rate 4.16 --num-prompts 1248 --port 12348 --metric-percentiles "25,50,75,90,95,99" --seed 1620 --endpoint /v1/completions
vllm bench serve --model /mnt/Qwen3-4B --dataset-name sharegpt --dataset-path /home/datasets/ShareGPT_V3_unfiltered_cleaned_split.json  --request-rate 3.12 --num-prompts 936 --port 12349 --metric-percentiles "25,50,75,90,95,99" --seed 1620 --endpoint /v1/completions
```

When I run these benchmarks, the llama3.1-8B incurs the following errors:
```
ERROR: /tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/ftensor.cpp:75: Page 112 is already mapped.
ERROR: /tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/ftensor.cpp:75: Page 745 is already mapped
/tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/page.cpp:24 cuMemCreate(&handle_, kPageSize, &prop, 0) failed in CUDA driver (2): out of memory
```
I am wondering whether kvcached provides a unified KV-cache manager.
When I use kvtop to view memory usage, each instance appears to allocate KV cache greedily, without considering the total available free memory across the two GPUs. 

<img width="780" height="347" alt="Image" src="https://github.com/user-attachments/assets/cef4ef4a-509c-4379-bff1-a197830de451" />

My test environment is as follows:
```
vLLM 0.11.0
kvcached 0.1.2 (installed via pip)
CUDA 12.4
PyTorch 2.8.0
2× A100 80GB GPUs
Ubuntu 22.04
```

**Comment by jiarong0907** [comment]
Hi @Ltryxcy, thanks for using kvcached.

This seems to be a bug. @ivanium do you have any ideas?

> ERROR: /tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/ftensor.cpp:75: Page 112 is already mapped.
ERROR: /tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/ftensor.cpp:75: Page 745 is already mapped
/tmp/pip-install-y6ja0vyp/kvcached_32ecdf44025a4bd5b524cceff3832c20/csrc/page.cpp:24 cuMemCreate(&handle_, kPageSize, &prop, 0) failed in CUDA driver (2): out of memory 

kvcached has unified memory for KV cache on a single GPU. It doesn't support unified memory across GPUs.

Can you explain a bit more what you mean by "each instance appears to allocate KV cache greedily"? From the screenshot, I can see kvcached allocates only the memory for model weights and no physical memory is allocated for KV cache. The number in the middle shows the upper bound memory size the instance can use.
 
>I am wondering whether kvcached provides a unified KV-cache manager.
When I use kvtop to view memory usage, each instance appears to allocate KV cache greedily, without considering the total available free memory across the two GPUs.

**Comment by Ltryxcy** [comment]
> Can you explain a bit more what you mean by "each instance appears to allocate KV cache greedily"? From the screenshot, I can see kvcached allocates only the memory for model weights, and no physical memory is allocated for KV cache. The number in the middle shows the upper bound memory size the instance can use

Thank you for your response! I observed that if each instance is assigned a distinct exported IPC name, then the KV-cache memory accounting becomes incorrect. When inspecting the KV space using kvtop, each instance appears to assume it has the full KV-cache budget and does not see the KV usage of other colocated models.

For example, in my setup LLAMA-8B, Qwen-8B, and Qwen-4B are colocated on the same GPUs (LLAMA-8B and Qwen-8B using tp_size = 2, Qwen-4B using tp_size = 1). Ideally, they should share and observe the same available KV-cache space. However, each instance continues allocating KV cache independently until it hits its own upper bound, eventually causing an OOM error.

**Comment by Ltryxcy** [comment]
> For the first issue, does it presist after applying the TP socket fix? If so, I may need to dig deeper because current log does not show sufficient clues. One possible cause here could be the engine checks the available GPU memory first and thought there is sufficient memory, but before it allocates the KV cache, some other engine takes the memory first, causing the first engine to fail.

Thanks. This issue no longer occurs after I fixed the TP communication sockets.
